### ISSUE TITLE
Toggle Auto eat issue

### ISSUE THREAD

**Issue by NekoBlek** [tonsit/valheim-mods#2]
I did not know the toggle was a thing until I checked the actual mod page on the site. The r2modman client had little to no info on it. Config editor was limited so I decided to read up on what's what. 

So I learned the toggle was shift+T and toggled it while on the server. On my screen it just kept saying "Glutton: True" every time I pressed it. I was puzzled so I kept pressing it and nothing happened. Then one person on the server was asking why "Glutton: False" was appearing on the screen. He told me that it only ever said disable for him, and enable for me. Weird thing is, no one else on the server has the mod, only me. 

Everything else works, except the toggle. 

I know you'll probably say something like "The server and/or other people need the mod too", however I wanted to bring it up anyway.

**Comment by tonsit** [comment]
Actually, no one else should need this mod (for that feature). The majority of the changes are done client side. I may be grabbing the player from an unreliable source, which may result in a random player being returned. I'll take a look at this in multiplayer to see if I can reproduce.

**Comment by tonsit** [comment]
Also, the config editor will provide context when you mouse over the options -- however -- there is a glitch where unless you have your inventory open, the mouse doesn't pop up the tooltip. Open your inventory and then enter the configuration and it should provide all the necessary context form within the game. 

I'll see if I can add more information to the r2modman package manifest.
