### ISSUE TITLE
Glutton consumed health potion for 3rd food

### ISSUE THREAD

**Issue by nwesterhausen** [tonsit/valheim-mods#3]
Reading through the config/info didn't seem like it would consume potions. I had 2 foods eaten and put some health pots in my inventory and one was immediately consumed. Not what I want :) 

If this is intended I would love an option to disable glutton consuming potions.

**Comment by tonsit** [comment]
This is a bug, I will need to add a filter around the inventory returned because the code calls for all Consumables, which includes pots,
